# https://pre-commit.com/
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.240'
    hooks:
      - id: ruff
        args: [--fix]

  # https://github.com/python/black#version-control-integration
  - repo: https://github.com/python/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
      - id: nbqa-black
      - id: nbqa-ruff

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        args: [--keep-output, --extra-keys=metadata.kernelspec metadata.language_info.version]
