# https://pre-commit.com/
repos:
  # isort should run before black as black sometimes tweaks the isort output
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: .+\.py$

  # https://github.com/python/black#version-control-integration
  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
      - id: black-jupyter

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        args: [--keep-output, --extra-keys=metadata.kernelspec metadata.language_info.version]
