name: pump
channels:
  - conda-forge
  - pyviz
dependencies:
  - bottleneck
  - cachey
  - cf_xarray
  - cftime
  - dask
  - dask_labextension
  - distributed
  - h5py
  - hdf5
  - ipympl
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - jupyter-server-proxy
  - matplotlib
  - nc-time-axis
  - nodejs
  - notebook
  - numba
  - pandas=1.1.0
  - pep8
  - pip
  - seawater
  - xarray
  - xgcm
  - xmitgcm
  - zarr
  - pip:
    - dask_jobqueue
    - ncar_jobqueue
    - git+https://github.com/dcherian/pump.git
    - git+https://github.com/hetland/xroms.git
    - git+https://github.com/dcherian/xcoare.git
