name: pump
channels:
  - conda-forge
  - pyviz
  - nodefaults
dependencies:
  - bottleneck
  - cachey
  - cartopy
  - cf_xarray
  - cftime
  - colorcet
  - dask
  - dask_labextension
  - prometheus_client
  - xarray-datatree
  - distributed
  - flox
  - gsw
  - gsw-xarray
  - h5py
  - hdf5
  - intake
  - intake-xarray
  - ecgtools
  - fsspec
  - hvplot
  - geoviews
  - kerchunk
  - h5netcdf
  - pydantic
  - intake-esm
  - ipympl
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - jupyter-server-proxy
  - mamba
  - matplotlib
  - netcdf4==1.6.0
  - nc-time-axis
  - nodejs
  - notebook
  - numba
  - pandas
  - pep8
  - pip
  - rich
  - seaborn
  - seawater
  - scipy
  - tqdm
  - xarray
  - xarray-datatree
  - xgcm<0.7
  - xhistogram
  - xmitgcm
  - watermark
  - zarr
  - ncar-jobqueue
  - dask-jobqueue
  - pip:
    - git+https://github.com/dcherian/pump.git
    - git+https://github.com/dcherian/dcpy.git
    - git+https://github.com/hetland/xroms.git
    - git+https://github.com/dcherian/xfilter.git
    - git+https://github.com/dcherian/xcoare.git
