name: pump
channels:
  - conda-forge
  - pyviz
  - nodefaults
dependencies:
  - bottleneck
  - cachey
  - cartopy
  - cf_xarray
  - cftime
  - colorcet
  - dask
  - dask_labextension
  - xarray-datatree
  - distributed
  - flox
  - gsw
  - h5py
  - hdf5
  - intake
  - intake-xarray
  - flox
  - ecgtools
  - fsspec
  - geoviews
  - h5netcdf
  - pydantic
  - intake-esm
  - ipympl
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - jupyter-server-proxy
  - matplotlib
  - netcdf4
  - nc-time-axis
  - nodejs
  - notebook
  - numba
  - pandas
  - pep8
  - pip
  - seaborn
  - seawater
  - scipy
  - tqdm
  - xarray
  - xarray-datatree
  - xgcm
  - xhistogram
  - xmitgcm
  - watermark
  - zarr
  - pip:
    - dask_jobqueue
    - ncar_jobqueue
    - gsw_xarray
    - git+https://github.com/dcherian/pump.git
    - git+https://github.com/dcherian/dcpy.git
    - git+https://github.com/hetland/xroms.git
    - git+https://github.com/dcherian/xfilter.git
    - git+https://github.com/dcherian/xcoare.git
