#!/usr/bin/env bash

set -xeo pipefail

# export PATH="$INSTALL_DIR/bin:$PATH"

# Install jupyterlab extensions
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @jupyterlab/toc \
                             dask-labextension \
                             @pyviz/jupyterlab_pyviz \
                             @bokeh/jupyter_bokeh \
                             @ryantam626/jupyterlab_code_formatter \
                             jupyter-matplotlib

jupyter serverextension enable --sys-prefix --py jupyterlab_code_formatter
jupyter serverextension enable --sys-prefix --py jupyter_server_proxy
jupyter serverextension enable --sys-prefix --py dask_labextension
